### ISSUE TITLE
Crashes on Aarch64

### ISSUE THREAD

**Issue by rehwanne** [oxzi/gosh#63] opened 2024-10-15 18:49 UTC
Hi, 
building the Code from Main branch like in the readme works but running it results in a crash:
```
./gosh -config gosh.yml -verbose
time=2024-10-15T18:46:33.195Z level=DEBUG msg="Starting webserver child" child=webserver config="map[Contact:nobody@example.com CustomIndex: ItemConfig:map[MaxLifetime:8.64e+13 MaxSize:10MiB MimeDrop:[application/vnd.microsoft.portable-executable application/x-msdownload] MimeMap:map[text/html:text/plain]] Listen:map[Bound::8080 Protocol:tcp] Protocol:http StaticFiles:<nil> UnixSocket:map[Chmod: Group: Owner:] UrlPrefix:]"
time=2024-10-15T18:46:33.195Z level=DEBUG msg="Starting store child" child=store config="map[IdGenerator:map[File: Length:8 Type:random] Path:./store]"
time=2024-10-15T18:46:33.199Z level=INFO msg="Opening Store" child=store directory=/
time=2024-10-15T18:46:33.362Z level=ERROR msg="The store subprocess has stopped, cleaning up"
time=2024-10-15T18:46:33.364Z level=INFO msg="Stopping webserver" child=webserver

```
System
Linux nixos 6.6.54 #1-NixOS SMP Fri Oct  4 14:30:05 UTC 2024 aarch64 GNU/Linux

**Comment by oxzi** [comment] 2024-10-16 21:32
Moin, thanks for trying gosh and reporting back this issue.

As I hadn't any aarch64 machines at hand, I had to fiddle with qemu first. After finally having virtualized an aarch64, I was able to reproduce your issue. To be concrete.

```
foo:~/gosh$ doas ./gosh -fork-child store -config gosh.yml -verbose
{"time":"2024-10-16T20:43:35.47791905Z","level":"DEBUG","msg":"Starting store child","config":{"Path":"./store","IdGenerator":{"Type":"random","Length":8,"File":""}}}
{"time":"2024-10-16T20:43:35.531133849Z","level":"INFO","msg":"Opening Store","directory":"/"}
Bad system call

foo:~/gosh$ doas strace ./gosh -fork-child store -config gosh.yml -verbose
[snip]
newfstatat(AT_FDCWD, "/", 0x400008a4b8, 0) = -1 ENETDOWN (Network is down)
+++ killed by SIGSYS +++
Bad system call
```

When removing the [seccomp-bpf sandbox for Linux](https://github.com/oxzi/gosh/blob/b4997cb98e393dc8654ec0e2c2a51b423cda6d21/gosh_store.go#L73-L95) temporary, the code works. Thus, it's some platform-specific mess for the hardening. Yay.

When just adding `newfstatat` to the allow list, a new error emerges:

```
{"time":"2024-10-16T20:54:42.726912548Z","level":"ERROR","msg":"Failed to apply seccomp-bpf filter","error":"failed to assemble policy: found unknown syscalls for arch aarch64: newfstatat"}
```

So far, so good. As `newfstatat` is being [part of `@system-service`](https://github.com/oxzi/syscallset-go/blob/041ebb1634ddb933e2ec17a02a416a832e361262/syscalls.go#L1353), it should already be available.

However, as the error says, this syscall is unknown for aarch64. Due to [this table](https://gpages.juszkiewicz.com.pl/syscalls-table/syscalls.html), Linux has this syscall for aarch64.

Thus, going deeper, I landed at [go-seccomp-bpf](https://github.com/elastic/go-seccomp-bpf) which my syscallset-go library uses for low-level seccomp-bpf magic. This library does not know of any `newfstatat` for aarch64 or arm despite being listed in the table above..

When adding `auditd` to the soup, I received the following log message:
```
type=SECCOMP msg=audit(1729113564.196:15): auid=4294967295 uid=1001 gid=1001 ses=4294967295 pid=4929 comm="gosh" exe="/home/user/gosh/gosh" sig=31 arch=c00000b7 syscall=79 compat=0 ip=0x15b40 code=0x80000000]AUID="unset" UID="_gosh" GID="_gosh" ARCH=aarch64 SYSCALL=unknown-syscall(-1)
```
The mentioned syscall number 79 is, btw, just the same as in the syscall table. However, I am a bit unsettled that it does list it as _unknown-syscall_.

As the [go-seccomp-bpf library lists `fstatat` as syscall 79 and [this random kernel file](https://raw.githubusercontent.com/torvalds/linux/v6.11/include/uapi/asm-generic/unistd.h) aliases `#define __NR_newfstatat __NR3264_fstatat` and `#define __NR3264_fstatat 79`, I just added `fstatat` to the allow list and, it worked. This is not satisfying.

I pushed a one-line-diff to main. Please try this one again.

**Comment by rehwanne** [comment] 2024-10-21 09:19
Not it totally works:

```
./gosh -config gosh.yml -verbose
time=2024-10-21T09:18:48.198Z level=DEBUG msg="Starting store child" child=store config="map[IdGenerator:map[File: Length:8 Type:random] Path:./store]"
time=2024-10-21T09:18:48.199Z level=DEBUG msg="Starting webserver child" child=webserver config="map[Contact:nobody@example.com CustomIndex: ItemConfig:map[MaxLifetime:8.64e+13 MaxSize:10MiB MimeDrop:[application/vnd.microsoft.portable-executable application/x-msdownload] MimeMap:map[text/html:text/plain]] Listen:map[Bound::8080 Protocol:tcp] Protocol:http StaticFiles:<nil> UnixSocket:map[Chmod: Group: Owner:] UrlPrefix:]"
time=2024-10-21T09:18:48.205Z level=INFO msg="Opening Store" child=store directory=/
time=2024-10-21T09:18:48.209Z level=INFO msg="All 0 tables opened in 0s\n" child=store producer=badger
time=2024-10-21T09:18:48.211Z level=INFO msg="Discard stats nextEmptySlot: 0\n" child=store producer=badger
time=2024-10-21T09:18:48.211Z level=INFO msg="Set nextTxnTs to 0" child=store producer=badger
```

**Comment by oxzi** [comment] 2024-10-22 06:46
Glad to hear that. If you experience any further issues, please let them coming.

**Closed by oxzi** 2024-10-22 06:46 UTC
